package ngeneanalysys.code.enums;

/**
 * 국가코드
 * 
 * @author gjyoo
 * @since 2016. 6. 13. 오후 9:43:03
 */
public enum CountryCode {
	UNKNOWN("---", "-- Unknown --"),
	KOR("KOR", "South Korea"),
	USA("USA", "United States"),
	GBR("GBR", "United Kingdom"),
	CAN("CAN", "Canada"),
	JPN("JPN", "Japan"),
	CHN("CHN", "China"),
	AFG("AFG", "Afghanistan"),
	ALB("ALB", "Albania"),
	DZA("DZA", "Algeria"),
	ASM("ASM", "American Samoa"),
	AND("AND", "Andorra"),
	AGO("AGO", "Angola"),
	AIA("AIA", "Anguilla"),
	ATA("ATA", "Antarctica"),
	ATG("ATG", "Antigua and Barbuda"),
	ARG("ARG", "Argentina"),
	ARM("ARM", "Armenia"),
	ABW("ABW", "Aruba"),
	AUS("AUS", "Australia"),
	AUT("AUT", "Austria"),
	AZE("AZE", "Azerbaijan"),
	BHS("BHS", "Bahamas"),
	BHR("BHR", "Bahrain"),
	BGD("BGD", "Bangladesh"),
	BRB("BRB", "Barbados"),
	BLR("BLR", "Belarus"),
	BEL("BEL", "Belgium"),
	BLZ("BLZ", "Belize"),
	BEN("BEN", "Benin"),
	BMU("BMU", "Bermuda"),
	BTN("BTN", "Bhutan"),
	BOL("BOL", "Bolivia"),
	BIH("BIH", "Bosnia and Herzegovina"),
	BWA("BWA", "Botswana"),
	BRA("BRA", "Brazil"),
	IOT("IOT", "British Indian Ocean Territory"),
	VGB("VGB", "British Virgin Islands"),
	BRN("BRN", "Brunei"),
	BGR("BGR", "Bulgaria"),
	BFA("BFA", "Burkina Faso"),
	BDI("BDI", "Burundi"),
	KHM("KHM", "Cambodia"),
	CMR("CMR", "Cameroon"),
	CPV("CPV", "Cape Verde"),
	CYM("CYM", "Cayman Islands"),
	CAF("CAF", "Central African Republic"),
	TCD("TCD", "Chad"),
	CHL("CHL", "Chile"),
	CXR("CXR", "Christmas Island"),
	CCK("CCK", "Cocos Islands"),
	COL("COL", "Colombia"),
	COM("COM", "Comoros"),
	COK("COK", "Cook Islands"),
	CRI("CRI", "Costa Rica"),
	HRV("HRV", "Croatia"),
	CUB("CUB", "Cuba"),
	CUW("CUW", "Curacao"),
	CYP("CYP", "Cyprus"),
	CZE("CZE", "Czech Republic"),
	COD("COD", "Democratic Republic of the Congo"),
	DNK("DNK", "Denmark"),
	DJI("DJI", "Djibouti"),
	DMA("DMA", "Dominica"),
	DOM("DOM", "Dominican Republic"),
	TLS("TLS", "East Timor"),
	ECU("ECU", "Ecuador"),
	EGY("EGY", "Egypt"),
	SLV("SLV", "El Salvador"),
	GNQ("GNQ", "Equatorial Guinea"),
	ERI("ERI", "Eritrea"),
	EST("EST", "Estonia"),
	ETH("ETH", "Ethiopia"),
	FLK("FLK", "Falkland Islands"),
	FRO("FRO", "Faroe Islands"),
	FJI("FJI", "Fiji"),
	FIN("FIN", "Finland"),
	FRA("FRA", "France"),
	PYF("PYF", "French Polynesia"),
	GAB("GAB", "Gabon"),
	GMB("GMB", "Gambia"),
	GEO("GEO", "Georgia"),
	DEU("DEU", "Germany"),
	GHA("GHA", "Ghana"),
	GIB("GIB", "Gibraltar"),
	GRC("GRC", "Greece"),
	GRL("GRL", "Greenland"),
	GRD("GRD", "Grenada"),
	GUM("GUM", "Guam"),
	GTM("GTM", "Guatemala"),
	GGY("GGY", "Guernsey"),
	GIN("GIN", "Guinea"),
	GNB("GNB", "Guinea-Bissau"),
	GUY("GUY", "Guyana"),
	HTI("HTI", "Haiti"),
	HND("HND", "Honduras"),
	HKG("HKG", "Hong Kong"),
	HUN("HUN", "Hungary"),
	ISL("ISL", "Iceland"),
	IND("IND", "India"),
	IDN("IDN", "Indonesia"),
	IRN("IRN", "Iran"),
	IRQ("IRQ", "Iraq"),
	IRL("IRL", "Ireland"),
	IMN("IMN", "Isle of Man"),
	ISR("ISR", "Israel"),
	ITA("ITA", "Italy"),
	CIV("CIV", "Ivory Coast"),
	JAM("JAM", "Jamaica"),
	JEY("JEY", "Jersey"),
	JOR("JOR", "Jordan"),
	KAZ("KAZ", "Kazakhstan"),
	KEN("KEN", "Kenya"),
	KIR("KIR", "Kiribati"),
	XKX("XKX", "Kosovo"),
	KWT("KWT", "Kuwait"),
	KGZ("KGZ", "Kyrgyzstan"),
	LAO("LAO", "Laos"),
	LVA("LVA", "Latvia"),
	LBN("LBN", "Lebanon"),
	LSO("LSO", "Lesotho"),
	LBR("LBR", "Liberia"),
	LBY("LBY", "Libya"),
	LIE("LIE", "Liechtenstein"),
	LTU("LTU", "Lithuania"),
	LUX("LUX", "Luxembourg"),
	MAC("MAC", "Macao"),
	MKD("MKD", "Macedonia"),
	MDG("MDG", "Madagascar"),
	MWI("MWI", "Malawi"),
	MYS("MYS", "Malaysia"),
	MDV("MDV", "Maldives"),
	MLI("MLI", "Mali"),
	MLT("MLT", "Malta"),
	MHL("MHL", "Marshall Islands"),
	MRT("MRT", "Mauritania"),
	MUS("MUS", "Mauritius"),
	MYT("MYT", "Mayotte"),
	MEX("MEX", "Mexico"),
	FSM("FSM", "Micronesia"),
	MDA("MDA", "Moldova"),
	MCO("MCO", "Monaco"),
	MNG("MNG", "Mongolia"),
	MNE("MNE", "Montenegro"),
	MSR("MSR", "Montserrat"),
	MAR("MAR", "Morocco"),
	MOZ("MOZ", "Mozambique"),
	MMR("MMR", "Myanmar"),
	NAM("NAM", "Namibia"),
	NRU("NRU", "Nauru"),
	NPL("NPL", "Nepal"),
	NLD("NLD", "Netherlands"),
	ANT("ANT", "Netherlands Antilles"),
	NCL("NCL", "New Caledonia"),
	NZL("NZL", "New Zealand"),
	NIC("NIC", "Nicaragua"),
	NER("NER", "Niger"),
	NGA("NGA", "Nigeria"),
	NIU("NIU", "Niue"),
	PRK("PRK", "North Korea"),
	MNP("MNP", "Northern Mariana Islands"),
	NOR("NOR", "Norway"),
	OMN("OMN", "Oman"),
	PAK("PAK", "Pakistan"),
	PLW("PLW", "Palau"),
	PSE("PSE", "Palestine"),
	PAN("PAN", "Panama"),
	PNG("PNG", "Papua New Guinea"),
	PRY("PRY", "Paraguay"),
	PER("PER", "Peru"),
	PHL("PHL", "Philippines"),
	PCN("PCN", "Pitcairn"),
	POL("POL", "Poland"),
	PRT("PRT", "Portugal"),
	PRI("PRI", "Puerto Rico"),
	QAT("QAT", "Qatar"),
	COG("COG", "Republic of the Congo"),
	REU("REU", "Reunion"),
	ROU("ROU", "Romania"),
	RUS("RUS", "Russia"),
	RWA("RWA", "Rwanda"),
	BLM("BLM", "Saint Barthelemy"),
	SHN("SHN", "Saint Helena"),
	KNA("KNA", "Saint Kitts and Nevis"),
	LCA("LCA", "Saint Lucia"),
	MAF("MAF", "Saint Martin"),
	SPM("SPM", "Saint Pierre and Miquelon"),
	VCT("VCT", "Saint Vincent and the Grenadines"),
	WSM("WSM", "Samoa"),
	SMR("SMR", "San Marino"),
	STP("STP", "Sao Tome and Principe"),
	SAU("SAU", "Saudi Arabia"),
	SEN("SEN", "Senegal"),
	SRB("SRB", "Serbia"),
	SYC("SYC", "Seychelles"),
	SLE("SLE", "Sierra Leone"),
	SGP("SGP", "Singapore"),
	SXM("SXM", "Sint Maarten"),
	SVK("SVK", "Slovakia"),
	SVN("SVN", "Slovenia"),
	SLB("SLB", "Solomon Islands"),
	SOM("SOM", "Somalia"),
	ZAF("ZAF", "South Africa"),
	SSD("SSD", "South Sudan"),
	ESP("ESP", "Spain"),
	LKA("LKA", "Sri Lanka"),
	SDN("SDN", "Sudan"),
	SUR("SUR", "Suriname"),
	SJM("SJM", "Svalbard and Jan Mayen"),
	SWZ("SWZ", "Swaziland"),
	SWE("SWE", "Sweden"),
	CHE("CHE", "Switzerland"),
	SYR("SYR", "Syria"),
	TWN("TWN", "Taiwan"),
	TJK("TJK", "Tajikistan"),
	TZA("TZA", "Tanzania"),
	THA("THA", "Thailand"),
	TGO("TGO", "Togo"),
	TKL("TKL", "Tokelau"),
	TON("TON", "Tonga"),
	TTO("TTO", "Trinidad and Tobago"),
	TUN("TUN", "Tunisia"),
	TUR("TUR", "Turkey"),
	TKM("TKM", "Turkmenistan"),
	TCA("TCA", "Turks and Caicos Islands"),
	TUV("TUV", "Tuvalu"),
	VIR("VIR", "U.S. Virgin Islands"),
	UGA("UGA", "Uganda"),
	UKR("UKR", "Ukraine"),
	ARE("ARE", "United Arab Emirates"),
	URY("URY", "Uruguay"),
	UZB("UZB", "Uzbekistan"),
	VUT("VUT", "Vanuatu"),
	VAT("VAT", "Vatican"),
	VEN("VEN", "Venezuela"),
	VNM("VNM", "Vietnam"),
	WLF("WLF", "Wallis and Futuna"),
	ESH("ESH", "Western Sahara"),
	YEM("YEM", "Yemen"),
	ZMB("ZMB", "Zambia"),
	ZWE("ZWE", "Zimbabwe");

	private String description;
	private String shortCode;

	private CountryCode(final String shortCode, final String description) {
		this.shortCode = shortCode;
		this.description = description;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(final String description) {
		this.description = description;
	}

	public String getShortCode() {
		return this.shortCode;
	}

	public void setShortCode(final String shortCode) {
		this.shortCode = shortCode;
	}
}
